version: '3'

services:
  cfml:
    container_name: cfml
    build:
     dockerfile: Dockerfile
    environment:
      BOX_SERVER_CFCONFIGFILE: myconfig.json
    image: cfml
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/app

