version: '3'

services:
  cfml:
    container_name: cfml
    build:
     dockerfile: Dockerfile
    image: cfml
    environment:
      BOX_SERVER_CFCONFIGFILE: myconfig.json
      CFPM_INSTALL: adminapi,administrator,mail,chart
      cfconfig_adminPassword: password
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/app

